SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO"; SET time_zone = "+00:00"; /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */; /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */; 
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */; /*!40101 SET NAMES utf8 */; -- -- Baza danych: `topr` -- -- -------------------------------------------------------- -- -- Struktura 
tabeli dla tabeli `temperature` -- DROP TABLE IF EXISTS `temperature`; CREATE TABLE IF NOT EXISTS `temperature` (
  `id` mediumint(9) NOT NULL AUTO_INCREMENT,
  `GORYCZKOWA` float DEFAULT NULL,
  `PIEC_STAWOW` float DEFAULT NULL,
  `MORSKIE_OKO` float DEFAULT NULL,
  `DATE_XML` datetime DEFAULT NULL,
  `DATE_SYSTEM` datetime DEFAULT NULL,
  PRIMARY KEY (`id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci AUTO_INCREMENT=21 ; /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */; /*!40101 SET 
CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */; /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
